apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 41.7.1
    helm:
      values: |
        grafana:
          adminPassword: admin
          service:
            type: NodePort
            nodePort: 32500
  syncPolicy:
    automated:
      prune: true
      selfHeal: true