apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 41.7.1
    helm:
      values: |
        grafana:
          service:
            type: NodePort
            nodePort: 30004
        prometheus:
          service:
            type: NodePort
            nodePort: 30003
  syncPolicy:
    automated:
      prune: true
      selfHeal: true