#helm install argocd .\charts\argo-cd\ --values .\charts\argo-cd\Values.yaml
argo-cd:
  dex:
    enabled: false
  server:
    service:
      type: NodePort
      nodePortHttp: 31862
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm